# 异常处理 Exception

**Artus** 要求各上层框架使用 `@artusjs/core` 提供的能力，实现如下规定的异常机制。同时要求上层框架生态系统中的插件/扩展，使用这一机制统一抛出错误。

预期可对**满足 Artus 规范的上层框架**中产生的异常构建全链路的**发现**与**用户自检**机制

## 错误码 ErrorCode

异常应当按照如下格式编制错误码，并在链路中使用错误码进行抛出和捕获

- `[NAMESPACE:]ERROR_CODE`
- 仅包括大写字母、数字 和 `_`
- NAMESPACE 为 `CORE` 的是 Artus 通用异常，上层框架不应使用，其详细内容见附录 1
- 不包括 NAMESPACE 的错误码用于业务代码自定义异常，框架及生态插件不应使用
- 所有未经 Artus 管理的 `Error` 默认具有错误码 `CORE:UNKNOWN`
- Artus 通用异常，未找到配置文件：`CORE:NO_CONFIGURATION`
- Gulu 框架中的 IO 超时异常：`GULU:IO_TIMEOUT`
- @gulu/redis 插件中的连接池为空异常：`GULU_REDIS:POOL_EMPTY`
- 业务代码中抛出的下游异常：`BIZA_FETCH_PLATFORM_FAIL`

错误码及对应描述应当在发布的 NPM 包被按如下格式的 YAML 或 JSON 文件中被编制：

注：描述字段支持使用对象格式声明 i18n，Language Code 使用 [ISO639-1:2002](https://www.loc.gov/standards/iso639-2/php/code_list.php)，其中 `en` 是默认值

```yaml
# ./artus-exception.yaml
GULU:IO_TIMEOUT:
    desc: IO 处理超时。
GULU:ADDRESS_USED:
    desc:
        zh: 待监听地址已被占用。
        en: Listen address already in use.
    detailUrl: https://www.bytedance.com
```

```json
// ./artus-exception.json
{
  "GULU:IO_TIMEOUT": {
    "desc": "IO 处理超时"
  },
  "GULU:ADDRESS_USED": {
    "desc": {
      "zh": "待监听地址已被占用。",
      "en": "Listen address already in use." 
    },
    "detailUrl": "https://www.bytedance.com"
  }
}
```

该文件将被 @artusjs/core 读取用于格式化异常

上层框架可通过插件树取得合并后的错误码表，用于自身的上报/自检平台建设

## 错误实体 StdError

```typescript
class StdError extends Error {
    name: string = 'StdError';
    _code: string;
    desc: string;
    detailUrl?: string;
    
    constructor (code: string) {
        super(`[${code}] This is Artus standard error, Please check on https://github.com/artusjs/error-code`);
        this._code = code;
    }
    
    get code(): string {
        return this._code;
    }
    
    get desc(): string {
        return ErrorCodeUtils.getI18NDesc(ErrorCodeMap[this._code]);
    }
    
    get detailUrl(): string|undefined {
        return ErrorCodeMap[this._code]?.detailUrl;
    }
}
```

## 抛出 Throw

框架应当在 `app` 或单例实例中，提供 `throwException` 和 `createException` 方法，定义如下

```typescript
interface BaseApplication {
    throwException(code: string): void;
    createException(code: string): StdError;
}
```

用户使用界面如下

```javascript
// any place

// use throwException
app.throwException('GULU:IO_TIMEOUT');

// use createException
const e = app.createException('GULU:IO_TIMEOUT');
throw e;
```

```typescript
// any place

@Injectable()
class AnyUserDefinedClass {
    @Inject()
    errorHandler: ErrorHandler; // Scope: Execution
  
    async aMethod(): Promise<void> {
        // use throwException
        this.errorHandler.throwException('GULU:IO_TIMEOUT');
        
        // use createException
        const e = this.errorHandler.createException('GULU:IO_TIMEOUT');
        throw e;
    }
}
```

## 捕获 Catch

工程中产生的所有未被用户主动 Catch 的错误，均应被框架 catch，并按各自诉求上报和打点（可观测性特性，社区版本提供基于 *OpenTelemetry* 的实现）。

同时，用户可通过主动配置 config 中的 onError 字段，处理错误并向终端用户响应该错误（参考 [koa-onerror](https://github.com/koajs/onerror)）

```javascript
// config.default.js
module.exports = (app) => {
    return {
        onerror: {
            all: (error, ctx) => {}, // if all exist, ignore negotiation
            text: (error, ctx) => {}, // text error handler (only for web)
            json: (error, ctx) => {}, // json error handler (only for web)
            html: (error, ctx) => {}, // html error handler (only for web)
            redirect: '', // if accepct html, can redirect to another error page
        },
    };
};
```
